name: Build On Demand

on:
  push:
    paths:
      - 'build-manifest.json'

jobs:
  trigger-builds:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Determine which programs to build
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        jq -c '.programs[] | select(.build == true)' build-manifest.json | while IFS= read -r program; do
          name=$(echo "$program" | jq -r '.name')
          path=$(echo "$program" | jq -r '.path')
          version=$(echo "$program" | jq -r '.version')
          copybookTag=$(echo "$program" | jq -r '.copybookTag')
          echo "name=$name" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_ENV
          echo "copybookTag=$copybookTag" >> $GITHUB_ENV
          echo "path=$path" >> $GITHUB_ENV

          if [[ $path == batch/* ]]; then
            program_type="batch"
          elif [[ $path == online/* ]]; then
            program_type="online"
          fi
          echo "program_type=$program_type" >> $GITHUB_ENV

          curl -X POST -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${program_type}-build.yml/dispatches" \
          -d '{"ref":"main","inputs":{"name":"'$name'","version":"'$version'","copybookTag":"'$copybookTag'"}}'
        done
      id: trigger
