name: Build Dispatcher Workflow

on:
  push:
    paths:
      - 'build-manifest.json'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install jq

    - name: Dispatch builds
      run: |
        jq -c '.programs[] | select(.build==true)' build-manifest.json | while read -r program; do
          name=$(echo $program | jq -r '.name')
          path=$(echo $program | jq -r '.path')
          version=$(echo $program | jq -r '.version')
          copybookTag=$(echo $program | jq -r '.copybookTag')
          workflow_file=""

          if [[ $path == batch/* ]]; then
            workflow_file="build-batch.yml"
          elif [[ $path == online/* ]]; then
            workflow_file="build-online.yml"
          fi

          echo "Dispatching build for $name"
          curl -X POST \
          -H "Authorization: token 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" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/fin8cloud/cobol-workflows-repo/actions/workflows/$workflow_file/dispatches \
          -d '{"ref":"main","inputs":{"program_name":"'"$name"'","program_version":"'"$version"'","copybook_tag":"'"$copybookTag"'"}}'
        done

    - name: Reset build flags in build-manifest.json
      run: |
        jq '.programs[] |= (.build = false)' build-manifest.json > temp.json && mv temp.json build-manifest.json

    - name: Commit changes to build-manifest.json
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add build-manifest.json
        git commit -m 'Reset build flags in build-manifest.json'
        git push
